<a href="https://colab.research.google.com/github/2303A54061/AI-ASSISTANCE-CODING/blob/main/LAB17_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SocialMediaTop100.csv**

In [71]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Number of records
n = 100

# Sample data
names = [f"User_{i}" for i in range(1, n+1)]

platforms = np.random.choice(
    ["Instagram", "Facebook", "Twitter", "TikTok", "LinkedIn"],
    n
)

followers = np.random.randint(100, 1000000, n)
following = np.random.randint(10, 5000, n)
posts = np.random.randint(1, 2000, n)
engagement_rate = np.round(np.random.uniform(0.1, 15.0, n), 2)

# Create DataFrame
social_df = pd.DataFrame({
    "PROFILE": names,
    "Platform": platforms,
    "Followers": followers,
    "Following": following,
    "Posts": posts,
    "Engagement_Rate": engagement_rate
})

# Save as CSV
social_df.to_csv("SocialMediaTop100.csv", index=False)

print("CSV file created successfully!")

# Show sample
social_df.head()

CSV file created successfully!

  PROFILE  Platform  Followers  Following  Posts  Engagement_Rate
0  User_1    TikTok     707711       3758   1187             7.82
1  User_2  LinkedIn     284906       4789   1744            13.17
2  User_3   Twitter     794924        673    957            11.14
3  User_4  LinkedIn      30635       2008   1705            10.49
4  User_5  LinkedIn     996207       3455    161            10.57

**weather_forecast_data.csv**

In [72]:
import pandas as pd
import numpy as np

# Reproducibility
np.random.seed(42)

# Number of records
n = 100

# Sample cities (you can change or extend)
cities = np.random.choice(
    ["Hyderabad", "Chennai", "Bangalore", "Delhi", "Mumbai"],
    n
)

# Generate synthetic weather data
temperature = np.round(np.random.uniform(15, 45, n), 1)   # °C
humidity = np.random.randint(20, 100, n)                  # %
wind_speed = np.round(np.random.uniform(0, 25, n), 1)     # km/h
pressure = np.random.randint(980, 1050, n)                # hPa

conditions = np.random.choice(
    ["Sunny", "Cloudy", "Rainy", "Stormy", "Foggy"],
    n
)

# Create DataFrame
weather_df = pd.DataFrame({
    "City": cities,
    "Temperature_C": temperature,
    "Humidity_%": humidity,
    "Wind_Speed_kmph": wind_speed,
    "Pressure_hPa": pressure,
    "Condition": conditions
})

# Save CSV
weather_df.to_csv("weather_forecast_data.csv", index=False)

print("weather_forecast_data.csv created successfully!")

# Show sample
weather_df.head()

weather_forecast_data.csv created successfully!

,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Pressure_hPa,Condition
0,Delhi,42.4,30,8.1,991,Cloudy
1,Mumbai,40.5,76,21.2,1046,Stormy
2,Bangalore,28.5,69,3.4,1044,Cloudy
3,Mumbai,17.9,42,17.7,1012,Stormy
4,Mumbai,26.1,50,13.8,1019,Stormy

**IMDB-Movie-Data.csv**

In [73]:
import pandas as pd
import random

# Sample data
titles = [
    "The Last Horizon", "Shadow Realm", "Golden Empire", "Silent Storm",
    "Neon Nights", "Broken Justice", "Lost Worlds", "Fire & Ice",
    "Dark Matter", "Hidden Truth"
]

genres = ["Action", "Drama", "Comedy", "Thriller", "Sci-Fi"]
directors = ["A. Kumar", "R. Sharma", "J. Smith", "L. Johnson", "M. Lee"]

data = []

for i in range(100):  # generate 100 movies
    data.append({
        "Rank": i + 1,
        "Title": random.choice(titles) + f" {i}",
        "Genre": random.choice(genres),
        "Description": "Sample movie description " + str(i),
        "Director": random.choice(directors),
        "Year": random.randint(2000, 2025),
        "Runtime (Minutes)": random.randint(80, 180),
        "Rating": round(random.uniform(5.0, 9.5), 1),
        "Votes": random.randint(10000, 2000000),
        "Revenue (Millions)": round(random.uniform(10, 300), 2),
        "Metascore": random.randint(30, 100)
    })

df = pd.DataFrame(data)

# Save to CSV
df.to_csv("IMDB-Movie-Data.csv", index=False)

print("IMDB-Movie-Data.csv generated successfully!")

IMDB-Movie-Data.csv generated successfully!

In [74]:
# Task 1
import statistics

def analyze_numbers(numbers):
    """
    Calculates and prints the mean, minimum, and maximum of a list of numbers.

    Args:
        numbers (list): A list of numerical values.
    """
    if not numbers:
        print("The list is empty. Cannot calculate statistics.")
        return

    mean_value = statistics.mean(numbers)
    min_value = min(numbers)
    max_value = max(numbers)

    print(f"List of numbers: {numbers}")
    print(f"Mean: {mean_value}")
    print(f"Minimum: {min_value}")
    print(f"Maximum: {max_value}")

# Run the function on the specified list
my_list = [12, 7, 9, 21, 5]
analyze_numbers(my_list)

List of numbers: [12, 7, 9, 21, 5]
Mean: 10.8
Minimum: 5
Maximum: 21

In [75]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load the dataset
social_df = pd.read_csv('SocialMediaTop100.csv', encoding='utf-8', engine='python')

# Remove duplicate user profiles based on 'PROFILE' and 'Platform'
social_df = social_df.drop_duplicates(subset=['PROFILE', 'Platform'])

# Handle missing values: fill numeric columns with median, categorical with mode
for col in social_df.columns:
    if social_df[col].dtype == 'O':
        social_df[col].fillna(social_df[col].mode()[0], inplace=True)
    else:
        social_df[col].fillna(social_df[col].median(), inplace=True)

# Encode categorical columns
label_encoders = {}
for col in social_df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    social_df[col] = le.fit_transform(social_df[col].astype(str))
    label_encoders[col] = le

# Show the cleaned and encoded dataframe
social_df.head()

/tmp/ipykernel_2103/3548318719.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  social_df[col].fillna(social_df[col].mode()[0], inplace=True)
/tmp/ipykernel_2103/3548318719.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  social_df[col].fillna(social_df[col].median(), inplace=True)

   PROFILE  Platform  Followers  Following  Posts  Engagement_Rate
0        0         3     707711       3758   1187             7.82
1       12         2     284906       4789   1744            13.17
2       23         4     794924        673    957            11.14
3       34         2      30635       2008   1705            10.49
4       45         2     996207       3455    161            10.57

In [76]:
import sqlite3
import pandas as pd

# Define the database file name and table name
db_file = 'social_media.db'
table_name = 'social_data'
csv_file = 'SocialMediaTop100.csv'

try:
    # Connect to SQLite database (creates it if it doesn't exist)
    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()

    # Load the CSV file into a Pandas DataFrame
    social_df_raw = pd.read_csv(csv_file, encoding='latin1', engine='python')

    # Write the DataFrame to an SQLite table
    social_df_raw.to_sql(table_name, conn, if_exists='replace', index=False)

    print(f"Successfully loaded '{csv_file}' into '{table_name}' table in '{db_file}'.")

except FileNotFoundError:
    print(f"Error: '{csv_file}' not found. Please upload the file to your Colab environment.")
except Exception as e:
    print(f"An error occurred: {e}")
finally:
    # Close the connection
    if 'conn' in locals() and conn:
        conn.close()

Successfully loaded 'SocialMediaTop100.csv' into 'social_data' table in 'social_media.db'.

### Querying Data from SQLite

Now, let's connect to the database and retrieve some data using SQL queries to verify the upload.

In [77]:
import sqlite3
import pandas as pd

db_file = 'social_media.db'
table_name = 'social_data'

try:
    conn = sqlite3.connect(db_file)

    # Query all data from the table
    query = f"SELECT * FROM {table_name} LIMIT 5;"
    df_from_db = pd.read_sql_query(query, conn)

    print("First 5 rows retrieved from the database:")
    display(df_from_db)

    # Example: Count rows
    count_query = f"SELECT COUNT(*) FROM {table_name};"
    total_rows = pd.read_sql_query(count_query, conn).iloc[0, 0]
    print(f"Total number of rows in '{table_name}': {total_rows}")

except Exception as e:
    print(f"An error occurred while querying the database: {e}")
finally:
    if 'conn' in locals() and conn:
        conn.close()

First 5 rows retrieved from the database:

  PROFILE  Platform  Followers  Following  Posts  Engagement_Rate
0  User_1    TikTok     707711       3758   1187             7.82
1  User_2  LinkedIn     284906       4789   1744            13.17
2  User_3   Twitter     794924        673    957            11.14
3  User_4  LinkedIn      30635       2008   1705            10.49
4  User_5  LinkedIn     996207       3455    161            10.57

Total number of rows in 'social_data': 100

In [78]:
import sqlite3
import pandas as pd

db_file = 'social_media.db'
table_name = 'social_data'

try:
    conn = sqlite3.connect(db_file)

    # Example SQL query: Select all data from the table
    query = f"SELECT * FROM {table_name} LIMIT 10;"
    df_queried = pd.read_sql_query(query, conn)

    print("First 10 rows from the social_data table:")
    display(df_queried)

except Exception as e:
    print(f"An error occurred while querying the database: {e}")
finally:
    if 'conn' in locals() and conn:
        conn.close()

First 10 rows from the social_data table:

   PROFILE  Platform  Followers  Following  Posts  Engagement_Rate
0   User_1    TikTok     707711       3758   1187             7.82
1   User_2  LinkedIn     284906       4789   1744            13.17
2   User_3   Twitter     794924        673    957            11.14
3   User_4  LinkedIn      30635       2008   1705            10.49
4   User_5  LinkedIn     996207       3455    161            10.57
5   User_6  Facebook     375813       3753   1604             5.46
6   User_7   Twitter     838788       1505    801             4.47
7   User_8   Twitter     351379       3314    398            12.16
8   User_9   Twitter     914010       3773   1301            12.17
9  User_10  LinkedIn     821754       1863    816            13.02

In [79]:
# Reload and preprocess the Social Media dataset with encoding fix
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Try reading with latin1 encoding to avoid UnicodeDecodeError
social_df = pd.read_csv('SocialMediaTop100.csv', encoding='latin1', engine='python')

# Remove duplicate user profiles based on 'PROFILE' and 'Platform'
social_df = social_df.drop_duplicates(subset=['PROFILE', 'Platform'])

# Handle missing values: fill numeric columns with median, categorical with mode
for col in social_df.columns:
    if social_df[col].dtype == 'O':
        social_df[col].fillna(social_df[col].mode()[0], inplace=True)
    else:
        social_df[col].fillna(social_df[col].median(), inplace=True)

# Encode categorical columns
label_encoders = {}
for col in social_df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    social_df[col] = le.fit_transform(social_df[col].astype(str))
    label_encoders[col] = le

# Show the cleaned and encoded dataframe
social_df.head()


# explanation in simple words:
# 1. We load the dataset from a CSV file.
# 2. We remove duplicate entries based on the 'PROFILE' and 'Platform' columns to ensure each user profile is unique.
# 3. We handle missing values by filling numeric columns with their median and categorical columns with their mode (most frequent value).
# 4. We encode categorical columns into numeric values using LabelEncoder, which converts each unique category into a number.

/tmp/ipykernel_2103/3990166605.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  social_df[col].fillna(social_df[col].mode()[0], inplace=True)
/tmp/ipykernel_2103/3990166605.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  social_df[col].fillna(social_df[col].median(), inplace=True)

   PROFILE  Platform  Followers  Following  Posts  Engagement_Rate
0        0         3     707711       3758   1187             7.82
1       12         2     284906       4789   1744            13.17
2       23         4     794924        673    957            11.14
3       34         2      30635       2008   1705            10.49
4       45         2     996207       3455    161            10.57

In [80]:
import pandas as pd
import numpy as np

# Load dataset
data = pd.read_csv('weather_forecast_data.csv')

# 1. Create Date column (since dataset doesn't have it)
data['Date'] = pd.date_range(start="2025-01-01", periods=len(data))

# 2. Convert to datetime
data['Date'] = pd.to_datetime(data['Date'])

# 3. Handle missing values (safe check)
for col in ['Temperature_C', 'Humidity_%']:
    if col in data.columns:
        data[col] = data[col].fillna(data[col].median())

# 4. Season feature engineering
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Autumn'

data['Season'] = data['Date'].dt.month.apply(get_season)

# 5. Week number feature
data['Week_Number'] = data['Date'].dt.isocalendar().week

# 6. Normalize temperature (instead of rainfall)
if 'Temperature_C' in data.columns:
    data['Temp_Normalized'] = (
        (data['Temperature_C'] - data['Temperature_C'].min()) /
        (data['Temperature_C'].max() - data['Temperature_C'].min())
    )

# Show result
data.head()

,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Pressure_hPa,Condition,Date,Season,Week_Number,Temp_Normalized
0,Delhi,42.4,30,8.1,991,Cloudy,2025-01-01,Winter,1,0.916388
1,Mumbai,40.5,76,21.2,1046,Stormy,2025-01-02,Winter,1,0.852843
2,Bangalore,28.5,69,3.4,1044,Cloudy,2025-01-03,Winter,1,0.451505
3,Mumbai,17.9,42,17.7,1012,Stormy,2025-01-04,Winter,1,0.096990
4,Mumbai,26.1,50,13.8,1019,Stormy,2025-01-05,Winter,1,0.371237

In [81]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer, MinMaxScaler

# Load the dataset
movies = pd.read_csv('IMDB-Movie-Data.csv')

# Remove duplicate movie entries based on Title and Year
movies = movies.drop_duplicates(subset=['Title', 'Year'])

# Handle missing values in 'Rating' and 'Genre'
if 'Rating' in movies.columns:
    movies['Rating'].fillna(movies['Rating'].median(), inplace=True)
if 'Genre' in movies.columns:
    movies['Genre'].fillna('Unknown', inplace=True)

# Encode 'Genre' as multi-hot (one-hot for each genre)
if 'Genre' in movies.columns:
    mlb = MultiLabelBinarizer()
    genre_lists = movies['Genre'].str.split(',')
    genre_encoded = mlb.fit_transform(genre_lists)
    genre_df = pd.DataFrame(genre_encoded, columns=mlb.classes_)
    movies = pd.concat([movies, genre_df], axis=1)

# Encode 'Language' if present
if 'Language' in movies.columns:
    movies['Language'] = movies['Language'].astype(str)
    movies['Language_encoded'] = movies['Language'].astype('category').cat.codes

# Scale 'Rating' between 0 and 1
if 'Rating' in movies.columns:
    scaler = MinMaxScaler()
    movies['Rating_scaled'] = scaler.fit_transform(movies[['Rating']])

# Save the cleaned and processed dataframe to a new CSV
movies.to_csv('IMDB-Movie-Data-processed.csv', index=False)

# Show the first few rows
print(movies.head())


# Explanation in simple words:
# 1. We load the movie dataset from a CSV file.
# 2. We remove duplicate movie entries based on Title and Year.
# 3. We handle missing values in 'Rating' and 'Genre'.
# 4. We encode 'Genre' as multi-hot (one-hot for each genre).
# 5. We encode 'Language' as numeric codes.
# 6. We scale 'Rating' to be between 0 and 1 using MinMaxScaler.

/tmp/ipykernel_2103/3754222007.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies['Rating'].fillna(movies['Rating'].median(), inplace=True)
/tmp/ipykernel_2103/3754222007.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies['Genre'].fillna('Unknown', inplace=True)

   Rank           Title   Genre                 Description    Director  Year  \
0     1  Hidden Truth 0   Drama  Sample movie description 0      M. Lee  2025
1     2   Lost Worlds 1   Drama  Sample movie description 1  L. Johnson  2018
2     3    Fire & Ice 2  Sci-Fi  Sample movie description 2    J. Smith  2001
3     4   Neon Nights 3  Comedy  Sample movie description 3   R. Sharma  2014
4     5  Shadow Realm 4  Comedy  Sample movie description 4   R. Sharma  2024

   Runtime (Minutes)  Rating    Votes  Revenue (Millions)  Metascore  Action  \
0                176     6.5   297427               69.88         35       0
1                140     7.4   580878              233.02         43       0
2                159     5.7  1672452               46.13         34       0
3                 85     5.3    69181              265.57         48       0
4                147     7.4  1834347              258.89         53       0

   Comedy  Drama  Sci-Fi  Thriller  Rating_scaled
0       0      1       0         0       0.318182
1       0      1       0         0       0.522727
2       0      0       1         0       0.136364
3       1      0       0         0       0.045455
4       1      0       0         0       0.522727